# Generated by Django 5.2.7 on 2025-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('2025-I', '2025-I'), ('2025-II', '2025-II'), ('2026-I', '2026-I'), ('2026-II', '2026-II')], db_index=True, default='2025-II', max_length=20),
        ),
    ]
