# Generated by Django 5.2.7 on 2025-10-30 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('teacher', models.ForeignKey(limit_choices_to={'role__name': 'Docente'}, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=10)),
                ('is_lab', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academics.course')),
            ],
            options={
                'verbose_name': 'Grupo/Sección',
                'verbose_name_plural': 'Grupos/Secciones',
                'unique_together': {('course', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('EX', 'Examen'), ('PC', 'Práctica/Control'), ('PR', 'Proyecto'), ('OT', 'Otro')], default='EX', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_points', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='exams/')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.coursegroup')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursegroup')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('student', 'course_group')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('uploaded_exam', models.FileField(blank=True, null=True, upload_to='exam_uploads/')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.assessment')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
